version: '3'

x-airline:
  &flight-template
  volumes:
    - type: bind
      source: ./data
      target: /data
    - type: bind
      source: ./templates
      target: /templates
    - type: bind
      source: ./pyproject.toml
      target: /app/pyproject.toml
x-twitter-secret:
  - &twitter-secret
    source: twitter_api
    target: twitter_api
x-env:
  &twitter-env
  TWITTER_API: /run/secrets/twitter_api

services:
  airline-1:
    <<: *flight-template
    # individual cmd for different airlines searched
    # sequences like these are not able to be merged
    # without the use of templating engine e.g. jinja
    command: [
      "--airline_iata", "ak",
    ]
    environment:
      <<: *twitter-env
      AVIATION_API: /run/secrets/aviation_api
    secrets:
      - *twitter-secret
      - source: av1_api
        target: aviation_api

  # each service is responsible for a different airline
  airline-2:
    <<: *flight-template
    command: [
      "--airline_iata", "mh",
    ]
    environment:
      <<: *twitter-env
      AVIATION_API: /run/secrets/aviation_api
    secrets:
      - *twitter-secret
      - source: av2_api
        target: aviation_api
  airline-3:
    <<: *flight-template
    command: [
      "--airline_iata", "sq",
    ]
    environment:
      <<: *twitter-env
      AVIATION_API: /run/secrets/aviation_api
    secrets:
      - *twitter-secret
      - source: av3_api
        target: aviation_api

secrets:
  twitter_api:
    file: secrets/twitter_api
  av1_api:
    file: secrets/av1_api
  av2_api:
    file: secrets/av2_api
  av3_api:
    file: secrets/av3_api
