services:
  flights-1: &flight_template
    image: asean-flight-logs:dev
    build:
      context: .
    command: [
      "--airline_iata", "ak",
      "--data_dir", "/data",
      "--template_dir", "/templates",
      "--loglevel", "info"
    ]
    env_file: # use separate .env to store separate api key
      - ./.env
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./templates
        target: /templates
      - type: bind
        source: ./asean_flight_logs/main.py
        target: /app/main.py
      - type: bind
        source: ./pyproject.toml
        target: /app/pyproject.toml
  flights-2:
    <<: *flight_template
    command: [
      "--airline_iata", "mh",
      "--data_dir", "/data",
      "--template_dir", "/templates",
      "--loglevel", "info"
    ]
    env_file:
      - ./.env
  flights-3:
    <<: *flight_template
    command: [
      "--airline_iata", "sq",
      "--data_dir", "/data",
      "--template_dir", "/templates",
      "--loglevel", "info"
    ]
    env_file:
      - ./.env

