services:
  app:
    container_name: flight-logs-container
    image: asean-flight-logs:dev
    build:
      context: .
    command: [
      "--airline_iata", "ak",
      "--data_dir", "/data",
      "--template_dir", "/templates",
      "--loglevel", "info"
    ]
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./templates
        target: /templates
      - type: bind
        source: ./asean_flight_logs/main.py
        target: /app/main.py
      - type: bind
        source: ./pyproject.toml
        target: /app/pyproject.toml
